config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pics do
    member do
      put "like", to: "pics#upvote"
    end
  end
  
  root 'pics#index'
  

end

app/models/pic.rb
class Pic < ActiveRecord::Base
    acts_as_votable
    belongs_to :user
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    # run: 'rails g paperclip pic image' and 'rake db:migrate' 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @pics = Pic.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @pic = current_user.pics.build
    end
    
    def create
        @pic = current_user.pics.build(pic_params)
        
        if @pic.save
            redirect_to @pic, notice: "Picture successfully posted!"
        else
            render 'new'
            
        end
    end
    
    def edit
    end
    
    def update
        if @pic.update(pic_params)
            redirect_to @pic, notice: "Post was updated!"
        else
            render 'edit'
        end
    end
    
    def destroy
        @pic.destroy
        redirect_to root_path
    end
    
    def upvote
        @pic.upvote_by current_user
        redirect_to :back
    end
    
    private 
    
    def pic_params
        params.require(:pic).permit(:title, :description, :image)
    end
    
    def find_pic
        @pic = Pic.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-invese">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "InstaClone", root_path %>
      </div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Post It!", new_pic_path %></li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Join Us!", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        </ul>
      <% end %>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pics/_form.html.erb
<%= simple_form_for @pic, html: { multipart: true } do |f| %>
  <% if @pic.errors.any? %>
    <div id="errors>">
      <h2><%= pluralize(@pic.errors.count, "error") %></h2>
      <br />
      <h2>Prevented this Pic from saving.</h2>
      <ul>
          <% @pic.erorrs.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>  
      </ul>
    </div>  
  <% end %> 
  
  <div class="form-group">
    <%= f.input :image, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :title, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: {class: 'form-control'} %>
  </div>
  <%= f.button :submit, class: "btn btn-info" %> 
<% end %>

app/views/pics/edit.html.erb
<div id="edit_page" class="col-md-8 col-md-offset-2">
    <div class="row">
        <div class="panel-panel-default">
            <div class="panel-heading">
                <h1>Fix picture!</h1>
            </div>
            <div class="panel-body">
                <div class="current_image">
                    <strong class="center">Right Now</strong>
                        <%= image_tag @pic.image.url %>
                </div>
                <%= render 'form' %>
                <br>
                <%= link_to "Cancel", pics_path, class: "btn btn-default" %>
            </div>
        </div>
    </div>
</div>

app/views/pics/index.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="transitions-enabled" id="pics">
        <% @pics.each do |pic| %>
            <div class="box panel panel-default">
                <%= link_to (image_tag pic.image.url), pic %>
                <h2><%= link_to pic.title, pic %></h2>
            </div>
        <% end %>
    </div>
</div>

app/views/pics/new.html.erb
<div class="col-md-8 col-md-offset-2">
    <div class="row">
        <div class="panel-panel-default">
            <div class="panel-heading">
                <h1>Post picture!</h1>
            </div>
            <div class="panel-body">
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/pics/show.html.erb
<div class="row" id="pic_show">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading pic_image">
                <%= image_tag @pic.image.url %>
            </div>
            <div class="panel-body">
                <h1><%= @pic.title %></h1>
                <hr>
                <p><%= @pic.description %></p>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-6">
                        <p class="user">By: <%= @pic.user.email %></p>
                    </div>
                    <div class="col md-6">
                        <div class="btn-group pull-right">
                            <%= link_to like_pic_path(@pic), method: :put, class: "btn btn-alert" do %>
                                <span class="glyphicon glyphicon-thumbs-up"></span>
                                <%= @pic.get_upvotes.size %>
                            <% end %>
                            <% if user_signed_in? %>
                                <%= link_to "Edit", edit_pic_path, class: "btn btn-info" %>
                                <%= link_to "Delete", pic_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"  %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>